
# def countdown_calculator():
#     ftime, ltime = input("enter first time :".title()), input(
#         "enter last time :".title())
#     ftime, ltime = ftime.split(" "), ltime.split(" ")
#     ftime, ltime = datetime.time(int(
#         ftime[0]), int(ftime[1])), datetime.time(int(ltime[0]), int(ltime[1]))
#     delta_time = ltime-ftime
#     print(f"number of hours left is {delta_time} ")


# # countdown_calculator()
# # time1=time.
# # time2=time(9,22,36)
# # print(time1,time2)
